media:
  input: public
  output: /
content:
  - name: index
    label: Homepage
    type: file
    path: src/content/index_page.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxLength: 100 } }
      - { name: landing, component: landing }
      - name: sections
        label: Sections
        type: block
        blockKey: type
        list: true
        blocks:
          - name: text_section
            label: Text Section
            component: section
          - name: cards_section
            label: Cards Section
            fields:
              - name: cards
                label: Cards
                component: card
                list: true
  - name: footer
    label: Footer
    type: file
    path: src/content/footer.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
      - { name: social_links, label: Social Links, component: social_links, list: true }
  - name: navbar
    label: Navbar
    type: file
    path: src/content/navbar.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: links, label: Links, component: button, list: true }
  - name: sponsors_page
    label: Sponsors page
    type: file
    path: src/content/sponsors_page.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxLength: 100 } }
      - name: sections
        label: Sections
        type: block
        blockKey: type
        list: true
        blocks:
          - name: text_section
            label: Text Section
            component: section
          - name: cards_section
            label: Cards Section
            fields:
              - name: cards
                label: Cards
                component: card
                list: true
  - name: sponsors
    label: Sponsors List
    type: file
    path: src/content/sponsors.json
    fields:
      - { name: sponsors, label: Sponsors, component: sponsor, list: true }
components:
  landing:
    label: Landing Section
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: rich-text
  section:
    label: Section
    fields:
      - name: title
        label: Section title
        type: string
      - name: body
        label: Section content
        type: rich-text
  social_links:
    label: Social Link
    fields:
      - name: name
        label: Name
        type: string
      - name: link
        label: Link
        type: string
      - name: icon
        label: Link Icon
        type: image
  button:
    label: Button
    fields:
      - name: title
        label: Title
        type: string
      - name: link
        label: Link
        type: string
  card:
    label: Card
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: button
        label: Button
        component: button
  sponsor:
    label: Sponsor
    fields:
      - name: name
        label: Name
        type: string
      - name: image
        label: Logo
        type: image
      - name: url
        label: Url
        type: string
      - name: description
        label: description
        type: string
