media:
  input: public
  output: /
content:
  - name: index
    label: Homepage
    type: file
    path: src/content/index_page.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxLength: 100 } }
      - { name: landing, component: landing }
      - name: sections
        label: Sections
        type: block
        blockKey: type
        list: true
        blocks:
          - name: text_section
            label: Text Section
            component: section
          - name: cards_section
            label: Cards Section
            fields:
              - name: cards
                label: Cards
                component: card
                list: true
      - name: statistics
        label: Statistics
        type: object
        list: true
        fields:
          - name: name
            label: Name
            type: string
          - name: value
            label: Value
            type: string
  - name: footer
    label: Footer
    type: file
    path: src/content/footer.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
      - { name: social_links, label: Social Links, component: social_link, list: true }
  - name: navbar
    label: Navbar
    type: file
    path: src/content/navbar.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: links, label: Links, component: link, list: true }
  - name: sponsors_page
    label: Sponsors page
    type: file
    path: src/content/sponsors_page.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxLength: 100 } }
      - name: sections
        label: Sections
        type: block
        blockKey: type
        list: true
        blocks:
          - name: text_section
            label: Text Section
            component: section
          - name: cards_section
            label: Cards Section
            fields:
              - name: cards
                label: Cards
                component: card
                list: true
  - name: projects_page
    label: Projects page
    type: file
    path: src/content/projects_page.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxLength: 100 } }
      - name: sections
        label: Sections
        type: block
        blockKey: type
        list: true
        blocks:
          - name: text_section
            label: Text Section
            component: section
          - name: cards_section
            label: Cards Section
            fields:
              - name: cards
                label: Cards
                component: card
                list: true
  - name: departments_page
    label: Departments page
    type: file
    path: src/content/departments_page.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxLength: 100 } }
      - name: sections
        label: Sections
        type: block
        blockKey: type
        list: true
        blocks:
          - name: text_section
            label: Text Section
            component: section
          - name: cards_section
            label: Cards Section
            fields:
              - name: cards
                label: Cards
                component: card
                list: true
  - name: contacts_page
    label: Contacts page
    type: file
    path: src/content/contacts_page.json
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxLength: 100 } }
      - name: sections
        label: Sections
        type: block
        blockKey: type
        list: true
        blocks:
          - name: text_section
            label: Text Section
            component: section
          - name: cards_section
            label: Cards Section
            fields:
              - name: cards
                label: Cards
                component: card
                list: true
  - name: sponsors
    label: Sponsors List
    type: file
    path: src/content/sponsors.json
    fields:
      - { name: sponsors, label: Sponsors, component: sponsor, list: true }
components:
  landing:
    label: Landing Section
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: rich-text
      - name: buttons
        label: Buttons
        component: button
        list:
          min: 1
          max: 2
  section:
    label: Section
    fields:
      - name: title
        label: Section title
        type: string
      - name: body
        label: Section content
        type: rich-text
  social_link:
    label: Social Link
    fields:
      - name: name
        label: Name
        type: string
      - name: url
        label: Url
        type: string
      - name: icon
        label: Social Icon
        type: image
  button:
    label: Button
    fields:
      - name: title
        label: Title
        type: string
      - name: url
        label: Url
        type: string
      - name: primary
        label: Primary
        type: boolean
        default: false
  link:
    label: Link
    fields:
      - name: title
        label: Title
        type: string
      - name: url
        label: Url
        type: string
  card:
    label: Card
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: button
        label: Button
        component: button
  sponsor:
    label: Sponsor
    fields:
      - name: name
        label: Name
        type: string
      - name: image
        label: Logo
        type: image
      - name: url
        label: Url
        type: string
      - name: description
        label: description
        type: string
